version: '3'

services:
  backend:
    build:
      context: ./app/backend
    ports:
      - '5000:5000'
    depends_on:
      - frontend

  frontend:
    build:
      context: ./app/frontend
    ports:
      - '3000:3000'
